blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions & Q&A
    url: https://github.com/amadshobi/goblin-vault/discussions
    about: Gunakan GitHub Discussions untuk bertukar pikiran, bertanya, atau diskusi umum seputar terminal & tooling.
